name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Generate Examples
        run: mkdir build && python examples/create_standalone_projects.py --output_directory=build

      - name: Publish Projects
        uses: actions/upload-artifact@v3
        with:
          name: ExampleProjects
          path: build
